#!/usr/bin/env python3
# -*- coding: UTF-8 -*-

from sys import argv, stdin
import yaml

yaml.CLoader.add_constructor('!u8', yaml.constructor.FullConstructor.construct_yaml_seq)

try:
    print(yaml.load(stdin.read(), Loader=yaml.CLoader)[0]['metadata'][argv[1]][0].replace("\0", "\n"))
except KeyError as e:
    print("null")
