# shellcheck shell=bash

# shellcheck source=src/usr/lib/rsetup/mod/block_helpers.sh
source "/usr/lib/rsetup/mod/block_helpers.sh"
source "/usr/lib/rsetup/mod/hwid.sh"

ALLOWED_RCONFIG_FUNC+=(
    "update_hostname"
    "update_locale"
    "enable_service"
    "disable_service"
    "resize_root"
    "set_thermal_governor"
    "set_led_trigger"
    "set_led_pattern"
    "set_led_netdev"
)

update_bootloader() {
    local pid device
    pid="${1:-$(get_product_id)}"
    __assert_f "/usr/lib/u-boot/$pid/setup.sh"

    device="${2:-$(__get_block_dev)}"

    "/usr/lib/u-boot/$pid/setup.sh" update_bootloader "$device"
}

erase_spinor() {
    local pid
    pid="${1:-$(get_product_id)}"
    __assert_f "/usr/lib/u-boot/$pid/setup.sh"

    "/usr/lib/u-boot/$pid/setup.sh" erase_spinor
}

update_spinor() {
    local pid
    pid="${1:-$(get_product_id)}"
    __assert_f "/usr/lib/u-boot/$pid/setup.sh"

    "/usr/lib/u-boot/$pid/setup.sh" update_spinor
}

erase_emmc_boot() {
    local pid device
    pid="${1:-$(get_product_id)}"
    __assert_f "/usr/lib/u-boot/$pid/setup.sh"

    for device in /dev/mmcblk*boot0
    do
        "/usr/lib/u-boot/$pid/setup.sh" erase_emmc_boot "$device"
    done
}

update_emmc_boot() {
    local pid device
    pid="${1:-$(get_product_id)}"
    __assert_f "/usr/lib/u-boot/$pid/setup.sh"

    for device in /dev/mmcblk*boot0
    do
        "/usr/lib/u-boot/$pid/setup.sh" update_emmc_boot "$device"
    done
}

update_hostname() {
    __parameter_count_check 1 "$@"

    local hostname="$1"

    echo "$hostname" > "/etc/hostname"
    cat << EOF > "/etc/hosts"
127.0.0.1 localhost
127.0.1.1 $hostname

# The following lines are desirable for IPv6 capable hosts
#::1     localhost ip6-localhost ip6-loopback
#fe00::0 ip6-localnet
#ff00::0 ip6-mcastprefix
#ff02::1 ip6-allnodes
#ff02::2 ip6-allrouters
EOF
}

update_locale() {
    __parameter_count_check 1 "$@"

    local locale="$1"
    echo "locales locales/default_environment_locale select $locale" | debconf-set-selections
    echo "locales locales/locales_to_be_generated multiselect $locale UTF-8" | debconf-set-selections
    rm "/etc/locale.gen"
    dpkg-reconfigure --frontend noninteractive locales
}

enable_service() {
    __parameter_count_check 1 "$@"

    local service="$1"
    systemctl enable --now "$service"
}

disable_service() {
    __parameter_count_check 1 "$@"

    local service="$1"
    systemctl disable --now "$service"
}

resize_root() {
    local root_dev filesystem
    root_dev="$(__get_root_dev)"
    filesystem="$(blkid -s TYPE -o value "$root_dev")"

    echo "Resizing root filesystem..."
    case "$filesystem" in
        ext4)
            resize2fs "$root_dev"
            ;;
        btrfs)
            btrfs filesystem resize max /
            ;;
        *)
            echo "Unknown filesystem." >&2
            return 1
            ;;
    esac
}

set_thermal_governor() {
    __parameter_count_check 1 "$@"

    local new_policy="$1" i
    for i in /sys/class/thermal/thermal_zone*/policy
    do
        echo "$new_policy" > "$i"
    done
}

RBUILD_DRIVER_ROOT_PATH="/sys/bus/platform/drivers"

RBUILD_LED_GPIO_DRIVER="leds-gpio"
RBUILD_LED_PWM_DRIVER="leds_pwm"

set_led_trigger() {
    __parameter_count_check 2 "$@"

    local led="$1" trigger="$2" node
    for node in "$RBUILD_DRIVER_ROOT_PATH/$RBUILD_LED_GPIO_DRIVER"/*/leds/"$led"/trigger "$RBUILD_DRIVER_ROOT_PATH/$RBUILD_LED_PWM_DRIVER"/*/leds/"$led"/trigger
    do
        echo "$trigger" > "$node"
    done
}

set_led_pattern() {
    local led="$1" node
    shift

    set_led_trigger "$led" pattern

    for node in "$RBUILD_DRIVER_ROOT_PATH/$RBUILD_LED_GPIO_DRIVER"/*/leds/"$led"/pattern "$RBUILD_DRIVER_ROOT_PATH/$RBUILD_LED_PWM_DRIVER"/*/leds/"$led"/pattern
    do
        echo "$*" > "$node"
    done
}

set_led_netdev() {
    __parameter_count_check 2 "$@"
    local led="$1" netdev="$2"

    set_led_trigger "$led" netdev

    for node in "$RBUILD_DRIVER_ROOT_PATH/$RBUILD_LED_GPIO_DRIVER"/*/leds/"$led"; do
        echo "$netdev" > "$node/device_name"
        echo "1" > "$node/link"
        echo "1" > "$node/tx"
        echo "1" > "$node/rx"
    done
}

set_getty_autologin() {
    local service="$1" systemd_override="/etc/systemd/system/$1.service.d" switch="$2" execstart user="$3"

    if [[ -n "$(systemctl list-units --no-legend "$service".service)" ]] || ! grep -q -e "disabled" -e "not-found" <(systemctl is-enabled "$service")
    then
        echo "$service is disabled."
        return 1
    fi

    if [[ "$switch" == "ON" ]]
    then
        mkdir -p "$systemd_override"

        if grep -q "serial" <<< "$systemd_override"
        then
            execstart="ExecStart=-/sbin/agetty --autologin $user --keep-baud 1500000,115200,57600,38400,9600 %I \$TERM"
        else
            execstart="ExecStart=-/sbin/agetty --autologin $user --noclear %I \$TERM"
        fi
        cat << EOF > "$systemd_override"/override.conf
# Auto generated by rsetup
# DO NOT MODIFY!
[Service]
ExecStart=
$execstart
EOF
    else
        rm -f "$systemd_override/override.conf"
    fi
}

set_sddm_autologin() {
    local config_dir="/etc/sddm.conf.d" switch="$1" user="$2"

    if [[ "$switch" == "ON" ]]
    then
        mkdir -p $config_dir
        cat << EOF | tee $config_dir/autologin.conf >/dev/null
[Autologin]
User=$user
Session=plasma
EOF
    else
        rm -f "$config_dir/50-rsetup-autologin.conf"
    fi
}

set_gdm_autologin() {
    local config_dir="/etc/gdm3" switch="$1"

    if [[ "$switch" == "ON" ]]
    then
        mkdir -p $config_dir
        sed -i '/^# Rsetup/,/# Rsetup$/d' $config_dir/daemon.conf
        cat << EOF | tee -a $config_dir/daemon.conf >/dev/null
# Rsetup
[daemon]
AutomaticLogin=$user
AutomaticLoginEnable=true
# Rsetup
EOF
    else
        sed -i '/^# Rsetup/,/# Rsetup$/d' $config_dir/daemon.conf
    fi
}

set_lightdm_autologin() {
    local config_dir="/etc/lightdm" switch="$1" user="$2"

    if [[ "$switch" == "ON" ]]
    then
        groupadd autologin
        gpasswd -a "$user" autologin
        mkdir -p $config_dir
        sed -i '/^# Rsetup/,/# Rsetup$/d' $config_dir/lightdm.conf
        cat << EOF | tee -a $config_dir/lightdm.conf >/dev/null
# Rsetup
[Seat:*]
autologin-user=$user
autologin-session=plasma
# Rsetup
EOF
    else
        sed -i '/^# Rsetup/,/# Rsetup$/d' $config_dir/lightdm.conf
    fi
}

get_autologin_status() {
    local service="$1"
    local status="OFF"

    if [[ -n "$(systemctl list-units --no-legend "$service".service)" ]]
    then
        if ! grep -q -e "disabled" -e "not-found" <(systemctl is-enabled "$service")
        then
            case "$service" in
            serial-getty@ttyAML0|serial-getty@ttyFIQ0|getty@tty1)
                if grep -q -e "--autologin" "/etc/systemd/system/$service.service.d/override.conf"
                then
                    status="ON"
                else
                    status="OFF"
                fi
                ;;
            sddm)
                if grep -q -e "[Autologin]" -e "User=" -e "Session=plasma" <(grep -v '^#' "/etc/sddm.conf.d/autologin.conf")
                then
                    status="ON"
                else
                    status="OFF"
                fi
                ;;
            gdm)
                if grep -q -e "AutomaticLogin=" -e "AutomaticLoginEnable=true" <(grep -v '^#' "/etc/gdm3/daemon.conf")
                then
                    status="ON"
                else
                    status="OFF"
                fi
                ;;
            lightdm)
                if grep -q -e "[Seat:*]" -e "autologin-user=" -e "autologin-session=plasma" <(grep -v '^#' "/etc/lightdm/lightdm.conf")
                then
                    status="ON"
                else
                    status="OFF"
                fi
                ;;
            esac
        fi
    fi
    echo "$status"
}

set_autologin_status() {
    local item="$1" switch="$2" user="$3"

    case "$item" in
    serial-getty@*|getty@*)
        set_getty_autologin "$item" "$switch" "$user"
        ;;
    sddm|gdm|lightdm)
        set_"$item"_autologin "$switch" "$user"
        ;;
    *)
        echo "Invalid options: $item" "$user"
        ;;
    esac
}
