#!/bin/bash

set -e

RSETUP_INTERACTIVE=0

source /lib/rsetup/utils.sh
source /lib/rsetup/block_helpers.sh

_first-boot() {
    dpkg-reconfigure -f noninteractive openssh-server

    local ROOT_DEV=$(_get_root_dev)
    local PART_ENTRY_NUMBER=$(udevadm info --query=property --name=$ROOT_DEV | grep '^ID_PART_ENTRY_NUMBER=' | cut -d'=' -f2)
    local PART_TABLE_TYPE=$(udevadm info --query=property --name=$ROOT_DEV | grep '^ID_PART_TABLE_TYPE=' | cut -d'=' -f2)
    local BLOCK_DEV=$(_get_block_dev)

    if [[ $PART_TABLE_TYPE == "gpt" ]]
    then
        sgdisk -e $BLOCK_DEV
        partprobe
    fi

    cat << EOF | parted ---pretend-input-tty $BLOCK_DEV
resizepart ${PART_ENTRY_NUMBER} 
yes
100%
EOF
    partprobe
    resize2fs $ROOT_DEV

    systemctl disable rsetup-first-boot.service
}

_update-uenv() {
    _parameter_count_check 1 "$@"
    _assert_f "/boot/uEnv-$1.txt"

    cp "/boot/uEnv-$1.txt" /boot/uEnv.txt
    echo "rootuuid=$(blkid --output value --match-tag UUID $(_get_root_dev))" >> /boot/uEnv.txt
}

update-bootloader() {
    _parameter_count_check 1 "$@"
    _assert_f "/usr/lib/u-boot-$1/u-boot.bin.sd.bin"

    local DEVICE=$(_get_block_dev)

    dd if=/usr/lib/u-boot-$1/u-boot.bin.sd.bin of=$DEVICE bs=1 count=444
    dd if=/usr/lib/u-boot-$1/u-boot.bin.sd.bin of=$DEVICE bs=512 skip=1
}

if (( $# == 0 )) || [[ $1 == main ]]
then
    main
else
    if [[ $(type -t $1) == function ]]
    then
        "$@"
    else
        echo $1 is not a valid function.
    fi
fi
