#!/bin/bash

LC_ALL="C"
LANG="C"
LANGUAGE="C"

if git status 1>/dev/null 2>&1 && [[ -f $PWD/root/usr/sbin/rsetup ]]
then
    ROOT_PATH="${ROOT_PATH:-"$PWD/root"}"
else
    ROOT_PATH="${ROOT_PATH:-"/"}"
fi

source "$ROOT_PATH/lib/rsetup/cli/main.sh"
source "$ROOT_PATH/lib/rsetup/tui/main.sh"

main() {
    register_screen __main
    while (( ${#RSETUP_SCREEN[@]} != 0 ))
    do
        ${RSETUP_SCREEN[-1]}
    done
}

if (( $# == 0 )) || [[ $1 == main ]]
then
    main
else
    if [[ $(type -t $1) == function ]]
    then
        set -e
        "$@"
    else
        echo $1 is not a valid function.
    fi
fi
